openapi: 3.0.0
info:
  version: '1'
  title: 'My100Movies API'
  description: 'My100Movies API Documentation'
components:
  schemas:
    Movie:
      type: object
      properties:
        id: 
          type: number
          description: Ticket id
          example: 23
        title: 
          type: string
          description: Movie title
          example: "Black Adam"
        releaseDate: 
          type: string
          description: Movie release date
          example: '2022-09-23'
    UserList:
      type: array
      items:
        type: object
        properties:
          id: 
            type: number
            description: Ticket id
            example: 23
          userId: 
            type: number
            description: User id
            example: 55
          movie:
            $ref: '#/components/schemas/Movie'
security:
  - bearerAuth: []
paths:
  /auth/register:
    post:
      summary: Register user 
      tags:
        - Authentication
      requestBody:
        required: true
        content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    example: 'user@mail.com'
                  password:
                    type: string
                    example: 'password'
      responses:
        '201':
          description: Account created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
                    example: User created
                  id: 
                    type: number
                    example: 12
        '400':
          description: Account not created
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: 
                    type: string
                    example: Email or phone number already in use
  /auth/login:
    post:
      summary: User login 
      tags:
        - Authentication
      requestBody:
        required: true
        content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    example: 'user@mail.com'
                  password:
                    type: string
                    example: 'password'
      responses:
        '200':
          description: Valid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  token: 
                    type: string
                    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyfSwiaWF0IjoxNjY4ODYyMDA4LCJleHAiOjE2NzE0NTQwMDh9.LcpTTOEb7hJ85cckRPiA304R7PgcBymASqEpHiPiWZM'
        '400':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: 
                    type: string
                    example: invalid credentials
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: 
                    type: string
                    example: user not found
  /movies:
    get:
      summary: Get all movies
      tags:
        - Movies
      parameters:
      - in: path
        name: page
        example: 2
        schema:
          type: integer
        description: Pagination
      responses:
        '200':
          description: Movies found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
        '403':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: 
                    type: string
                    example: bearer token required
    post:
      summary: Add movie to user list
      tags:
        - Movies
      requestBody:
        required: true
        content:
            application/json:
              schema:
                type: object
                properties:
                  movieId:
                    type: number
                    example: 23
                    description: Movie id from movie list endpoint
      responses:
        '201':
          description: Movie added
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
                    example: Movie added
  /movies/search:
    get:
      summary: Search movies
      tags:
        - Movies
      parameters:
      - in: path
        name: query
        example: 'black adam'
        schema:
          type: string
        description: Search query
      responses:
        '200':
          description: Movies found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
        '403':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: 
                    type: string
                    example: bearer token required
  /movies/{userId}:
    get:
      summary: Get user movies
      tags:
        - Movies
      parameters:
      - in: path
        name: userId
        example: 2
        schema:
          type: integer
        description: User id
      responses:
        '200':
          description: Movies found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserList'
        '403':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: 
                    type: string
                    example: bearer token required
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: 
                    type: string
                    example: user not found